### ISSUE TITLE
Add `store: true` flag on each Singer tap to allow storing extracted data in internal storage for use in downstream task (i.e. without requiring a target task)

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/plugin-singer#41]
Extend each tap to allow storing data extracted from a tap (without schema information) to internal storage.

```yaml
id: postgres_to_ion
namespace: dev
  
tasks:
  - id: extract
    type: io.kestra.plugin.singer.taps.PipelinewisePostgres
    store: true # ⬅️ THIS 
    docker:
      image: python:3.8
    host: localhost
    port: 5432
    dbName: postgres
    username: postgres
    password: "{{ secret('DB_PASSWORD') }}"
    streamsConfigurations:
      - replicationMethod: FULL_TABLE # FULL_TABLE, INCREMENTAL, LOG_BASED
        selected: true
```

This task might either return:
1. the schema + data in separate files
2. one file with data converted to the proper types.

The latter is preferable.

Ofc, this example is silly, as for Postgres there are already dedicated Query and CopyOut tasks, but for more complex source systems, this opens up the doors to useful patterns e.g. retrieving data from a specific system and then running tasks `ForEachItem`.

Not a high priority for now, but worth keeping in mind the possibility.
