### ISSUE TITLE
Singer plugin doesn't build

### ISSUE THREAD

**Issue by anna-geller** [kestra-io/plugin-singer#82]
Edit (Mathieu Gabelle):
Here's a reproducer
```
id: test_bigquery_ci_failure
namespace: mgabelle.tests.singer.bigquery

tasks:
  - id: test_singer
    type: io.kestra.plugin.singer.taps.BigQuery
    serviceAccount: "{{ secret('GOOGLE_SA')}}"
    startAlwaysInclusive: false
    startDateTime: "2013-09-08T16:19:12Z"
    limit: 1
    streams:
      - name: covid19_nyt_us_states
        table: bigquery-public-data.covid19_nyt.us_states
        columns:
          - date
          - state_name
          - confirmed_cases
          - deaths
        datetime_key: date
        filters:
          - "EXTRACT (YEAR from date) = 2020"
          - "EXTRACT (MONTH from date) = 3"
          - "state_fips_code = '66'"
    streamsConfigurations:
      - replicationMethod: FULL_TABLE
        selected: true
    pipPackages:
      - git+https://github.com/kestra-io/tap-bigquery.git@master
```

It seems two command are created :

- First one passes successfully 

```
Starting command with container id 5c0c0864731f37fc3551f4376ffb004607e050df8e7583d4d6f64234c4351182 [/bin/sh -c set -o errexit
 pip install pip --upgrade > /dev/null
 pip install --target . git+https://github.com/kestra-io/tap-bigquery.git@master > /dev/null
 pip install --target . python-json-logger > /dev/null
 chmod -R 755 bin
 find . -type f -name logging.conf | grep "/singer/" | xargs -r cp logging.conf
 ./bin/tap-bigquery --config config.json --discover > discover.json]
```
and we have output from bigquery : 
`{"asctime": "2024-12-02 14:05:11,765", "name": "getschema.impl", "levelname": "INFO", "message": "Inference completed from 17 records"}`

- Second one fails : 
```
Starting command with container id 85bd7dd23e6ea787d14d40fdd89e3296175d4ea90c64f30b68224bc92a427030 [/bin/sh -c set -o errexit
 pip install pip --upgrade > /dev/null
 pip install --target . git+https://github.com/kestra-io/tap-bigquery.git@master > /dev/null
 pip install --target . python-json-logger > /dev/null
 chmod -R 755 bin
 find . -type f -name logging.conf | grep "/singer/" | xargs -r cp logging.conf
 ./bin/tap-bigquery --config ./config.json --catalog ./catalog.json --state state.json > raw.jsonl]
```

with following error issue : 
![Image](https://github.com/user-attachments/assets/dd5f6f7f-eb67-49b7-8bcd-a05115d97549)

Seems related to a Python issue from tap-bigquery
